version: "3"
name: springboot-mysql-compose

services:
  app:
    container_name: booster-springboot
    build:
      context: .
      dockerfile: ./Dockerfile2
    image: quickybooster/springboot
    ports:
      - "8082:8080"
    # restart: on-failure
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - java-app

  mysql:
    container_name: booster-mysql
    image: "mysql:8.0"
    environment:
      MYSQL_ROOT_PASSWORD: Abc@123456
      MYSQL_DATABASE: db_example
      MYSQL_USER: booster
      MYSQL_PASSWORD: Abc@123456
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3306"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    volumes:
      - booster-mysql-data:/var/lib/mysql
    networks:
      - java-app

volumes:
  booster-mysql-data:
networks:
  java-app:
    name: java-app
